### ISSUE TITLE
Cant find CSN_setup.ipynb

### ISSUE THREAD

**Issue by erblinium** [Collection-Space-Navigator/CSN#2]
In the readme it says 
`
... Place your prepared dataset folders in the build/datasets directory and modify build/datasets/datasets_config.json. We recommend using our colab CSN_setup.ipynb to format your data correctly.
`

The file `CSN_setup.ipynb` is nowhere to be found.

**Comment by erblinium** [comment]
@mcanet, @tillmannohm

**Comment by mcanet** [comment]
Sorry for confusion, CSN_setup.ipynb was our old name. Now we have one version for colab ( CSN_colab.ipynb ) and another for version Jupyter notebook for local use ( CSN_notebook.ipynb ). 

To use colab version use this link:
[https://colab.research.google.com/github/Collection-Space-Navigator/CSN/blob/main/CSN_colab.ipynb](https://colab.research.google.com/github/Collection-Space-Navigator/CSN/blob/main/CSN_colab.ipynb)
